core:
  type: core
  preset: core500
  ip: "192.168.254.104"
  aux_axis: 6
  rail_offset: 100
  has_tool_changer: true

SBS_adapter_1:
  type: SBS_adapter
  attach:
    parent_name: core
    parent_solid: plate_2
    child_solid: SBS_adapter
    parent_anchor: E5
    child_anchor: hole_0



microplate_1:
  type: microplate
  attach:
    parent_name: SBS_adapter_1
    parent_solid: SBS_adapter
    child_solid: microplate
    parent_anchor: center
    child_anchor: center


microtube_A1:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: A1
    child_anchor: center
microtube_A2:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: A2
    child_anchor: center
microtube_A3:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: A3
    child_anchor: center
microtube_A4:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: A4
    child_anchor: center
microtube_A5:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: A5
    child_anchor: center
microtube_A6:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: A6
    child_anchor: center
microtube_A7:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: A7
    child_anchor: center
microtube_A8:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: A8
    child_anchor: center
microtube_A9:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: A9
    child_anchor: center
microtube_A10:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: A10
    child_anchor: center
microtube_A11:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: A11
    child_anchor: center
microtube_A12:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: A12
    child_anchor: center
microtube_B1:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: B1
    child_anchor: center
microtube_B2:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: B2
    child_anchor: center
microtube_B3:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: B3
    child_anchor: center
microtube_B4:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: B4
    child_anchor: center
microtube_B5:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: B5
    child_anchor: center
microtube_B6:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: B6
    child_anchor: center
microtube_B7:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: B7
    child_anchor: center
microtube_B8:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: B8
    child_anchor: center
microtube_B9:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: B9
    child_anchor: center
microtube_B10:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: B10
    child_anchor: center
microtube_B11:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: B11
    child_anchor: center
microtube_B12:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: B12
    child_anchor: center
microtube_C1:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: C1
    child_anchor: center
microtube_C2:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: C2
    child_anchor: center
microtube_C3:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: C3
    child_anchor: center
microtube_C4:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: C4
    child_anchor: center
microtube_C5:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: C5
    child_anchor: center
microtube_C6:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: C6
    child_anchor: center
microtube_C7:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: C7
    child_anchor: center
microtube_C8:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: C8
    child_anchor: center
microtube_C9:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: C9
    child_anchor: center
microtube_C10:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: C10
    child_anchor: center
microtube_C11:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: C11
    child_anchor: center
microtube_C12:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: C12
    child_anchor: center
microtube_D1:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: D1
    child_anchor: center
microtube_D2:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: D2
    child_anchor: center
microtube_D3:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: D3
    child_anchor: center
microtube_D4:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: D4
    child_anchor: center
microtube_D5:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: D5
    child_anchor: center
microtube_D6:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: D6
    child_anchor: center
microtube_D7:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: D7
    child_anchor: center
microtube_D8:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: D8
    child_anchor: center
microtube_D9:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: D9
    child_anchor: center
microtube_D10:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: D10
    child_anchor: center
microtube_D11:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: D11
    child_anchor: center
microtube_D12:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: D12
    child_anchor: center
microtube_E1:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: E1
    child_anchor: center
microtube_E2:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: E2
    child_anchor: center
microtube_E3:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: E3
    child_anchor: center
microtube_E4:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: E4
    child_anchor: center
microtube_E5:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: E5
    child_anchor: center
microtube_E6:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: E6
    child_anchor: center
microtube_E7:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: E7
    child_anchor: center
microtube_E8:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: E8
    child_anchor: center
microtube_E9:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: E9
    child_anchor: center
microtube_E10:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: E10
    child_anchor: center
microtube_E11:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: E11
    child_anchor: center
microtube_E12:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: E12
    child_anchor: center
microtube_F1:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: F1
    child_anchor: center
microtube_F2:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: F2
    child_anchor: center
microtube_F3:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: F3
    child_anchor: center
microtube_F4:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: F4
    child_anchor: center
microtube_F5:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: F5
    child_anchor: center
microtube_F6:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: F6
    child_anchor: center
microtube_F7:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: F7
    child_anchor: center
microtube_F8:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: F8
    child_anchor: center
microtube_F9:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: F9
    child_anchor: center
microtube_F10:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: F10
    child_anchor: center
microtube_F11:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: F11
    child_anchor: center
microtube_F12:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: F12
    child_anchor: center
microtube_G1:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: G1
    child_anchor: center
microtube_G2:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: G2
    child_anchor: center
microtube_G3:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: G3
    child_anchor: center
microtube_G4:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: G4
    child_anchor: center
microtube_G5:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: G5
    child_anchor: center
microtube_G6:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: G6
    child_anchor: center
microtube_G7:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: G7
    child_anchor: center
microtube_G8:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: G8
    child_anchor: center
microtube_G9:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: G9
    child_anchor: center
microtube_G10:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: G10
    child_anchor: center
microtube_G11:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: G11
    child_anchor: center
microtube_G12:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: G12
    child_anchor: center
microtube_H1:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: H1
    child_anchor: center
microtube_H2:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: H2
    child_anchor: center
microtube_H3:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: H3
    child_anchor: center
microtube_H4:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: H4
    child_anchor: center
microtube_H5:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: H5
    child_anchor: center
microtube_H6:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: H6
    child_anchor: center
microtube_H7:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: H7
    child_anchor: center
microtube_H8:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: H8
    child_anchor: center
microtube_H9:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: H9
    child_anchor: center
microtube_H10:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: H10
    child_anchor: center
microtube_H11:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: H11
    child_anchor: center
microtube_H12:
  type: microtube
  attach:
    parent_name: microplate_1
    parent_solid: microplate
    child_solid: microtube
    parent_anchor: H12
    child_anchor: center
