core:
  type: core
  preset: core500
  ip: "192.168.254.104"
  aux_axis: 6
  rail_offset: 100
  has_toolchanger: True 

SBS_adapter_1:
  type: SBS_adapter
  attach:
    parent_name: core
    parent_solid: plate_2
    parent_anchor: F5
    child_solid: SBS_adapter
    child_anchor: hole_0

microplate_1:
  type: microplate
  full: True
  attach:
    parent_name: SBS_adapter_1
    parent_solid: SBS_adapter
    parent_anchor: center
    child_solid: microplate
    child_anchor: center

SBS_adapter_2:
  type: SBS_adapter
  attach:
    parent_name: core
    parent_solid: plate_2
    parent_anchor: F12
    child_solid: SBS_adapter
    child_anchor: hole_0

microplate_2:
  type: microplate
  full: False
  attach:
    parent_name: SBS_adapter_2
    parent_solid: SBS_adapter
    parent_anchor: center
    child_solid: microplate
    child_anchor: center

tool_rack_1:
  type: tool_rack
  attach:
    parent_name: core
    parent_solid: plate_2
    parent_anchor: H20
    child_solid: tool_rack
    child_anchor: center

microtube_gripper_1:
  type: microtube_gripper
  has_toolchanger: True 
  attach:
    parent_name: tool_rack_1
    parent_solid: tool_rack
    parent_anchor: tool_connection
    child_solid: toolchanger_tool_side
    child_anchor: tool_rack_connection